import {
  ExpressJsDark,
  PostgreSQL,
  Prisma,
  Python,
  React,
  ReactRouter,
  JavaScript,
  HTML5,
  Webpack,
  Render,
  VercelDark,
  Netlify2,
  CSS3,
  NextJs,
  TypeScript,
  TailwindCSS,
  ShadcnUI,
  FastAPI,
  Docker,
  Cloudinary,
} from 'developer-icons';

import { Jwt, Passport, EJS, Zustand } from '../../shared/StackIcons';

const projectsDb = () => {
  const projects = {
    vyroom: {
      name: 'Vyroom',
      prvwUrl: 'https://vyroom.io',
      imgUrl: '/projects/vyroom.jpg',
      repoUrl: '',
      date: '2026',
      tag: 'Immobilier',
      desc: `Vyroom est une marketplace immobilière qui simplifie la recherche, la location et la découverte de biens en Côte d'Ivoire.`,
      stack: [TypeScript, Python],
    },
    skyup: {
      name: 'Skyup',
      prvwUrl: 'https://skyup-pi.vercel.app/',
      imgUrl: '/projects/skyup.png',
      repoUrl: 'https://github.com/chacka1315/skyup',
      date: '2026',
      tag: 'Social media',
      desc: `Un clone de X/Twitter avec authentification, fil d'actualité, posts, likes et gestion de profil.`,
      stack: [
        NextJs,
        TypeScript,
        TailwindCSS,
        ShadcnUI,
        Zustand,
        FastAPI,
        PostgreSQL,
        Jwt,
        Cloudinary,
        Docker,
        VercelDark,
      ],
    },
    blogapp: {
      name: 'Personal blog',
      prvwUrl: 'https://siakablog-web-d1yr.vercel.app/',
      imgUrl: '/projects/blog.png',
      repoUrl: 'https://github.com/chacka1315/blogsiaka',
      date: '2025',
      tag: 'Bloging',
      desc: `Une blog personnel permettant aux visiteurs de lire les articles et au prorpiétaire de gérer ses articles.  `,
      stack: [
        ExpressJsDark,
        Prisma,
        PostgreSQL,
        Jwt,
        Render,
        React,
        ReactRouter,
        VercelDark,
      ],
    },
    msgapp: {
      name: 'iChat',
      prvwUrl: 'https://messaging-app-client-five.vercel.app/',
      imgUrl: '/projects/message_app.png',
      repoUrl: 'https://github.com/chacka1315/messaging-app',
      date: '2025',
      tag: 'Social media',
      desc: `Un mini WhatsApp permettant envoies et réceptions de messages/images entre utilisateurs et les inscrits.`,
      stack: [
        ExpressJsDark,
        Prisma,
        PostgreSQL,
        Render,
        Jwt,
        React,
        ReactRouter,
        VercelDark,
      ],
    },
    waldo: {
      name: "Where's Waldo?",
      prvwUrl: 'https://waldogame.vercel.app/',
      imgUrl: '/projects/ws_waldo.jpg',
      repoUrl: 'https://github.com/chacka1315/where-is-waldo',
      date: '2025',
      tag: 'Gaming',
      desc: `Version online du célèbre jeu "Où est Charlie?", basé sur la recherche d'objets cachés dans des images.`,
      stack: [
        ExpressJsDark,
        Prisma,
        PostgreSQL,
        Render,
        React,
        ReactRouter,
        VercelDark,
      ],
    },
    uploader: {
      name: 'File uploader',
      prvwUrl: 'https://file-uploader-9dnb.onrender.com/',
      imgUrl: '/projects/uploader.png',
      repoUrl: 'https://github.com/chacka1315/file-uploader-app',
      date: '2025',
      tag: 'Cloud',
      desc: `Un mini Google Drive pour uploads et organisqtion de fichiers de façon simple et intuitive.`,
      stack: [ExpressJsDark, Prisma, PostgreSQL, Passport, EJS, Render],
    },
    // todo_list: {
    //   name: 'Todo list',
    //   prvwUrl: 'https://chacka1315.github.io/to-do-list/',
    //   imgUrl: `https://res.cloudinary.com/deeklaav9/image/upload/v1766526584/todo_list_yun7on.png`,
    //   repoUrl: 'https://github.com/chacka1315/to-do-list/tree/main',
    //   date: '2025',
    //   tag: 'Productivity',
    //   desc: `Application de gestion de tâches avec persistance locale des données des utilisateurs.`,
    //   stack: [HTML5, CSS3, JavaScript, Webpack],
    // },
  };
  const getProjects = () => projects;

  return { getProjects };
};

export const projectsData = projectsDb();
